# -*- coding: utf-8 -*-
"""App UI translations for nl, ru, tr, th, id, pt-PT, keyed by the English string.
Merged into the catalogs by build_catalogs.py. Model-written; spot-check before release."""

KEYS = ["%@, then %@.", "%@. Change currency", "%lld%% off Lifetime", "A price tag reading %@, converted to %@.",
        "About", "Active", "All data stored locally", "Allow camera", "Allow the camera.", "Auto-renews, cancel anytime.",
        "Best Value", "Calculator", "Camera access is off", "Clear search", "Close", "Continue",
        "Couldn't complete the purchase. Try again.", "Couldn't load plans. Check your connection.",
        "Couldn't reach the exchange rate service.", "Couldn't read the latest rates. Try again later.", "Currency", "day",
        "Detect local currency", "Exchange Rates",
        "Exchange rates are stored offline and can be updated when you have an internet connection.", "Free for %@",
        "Get started", "Home currency", "Home currency: %@. Tap to change.", "Last Updated", "Lifetime",
        "Manage Subscription", "month", "Monthly", "Most Popular", "No account required", "No ads or tracking",
        "No connection. Rates will update when you're online.", "No currency matches “%@”", "No thanks", "Not now",
        "Not subscribed", "OK", "one time", "One-time purchase of %@. No subscription.",
        "One-time purchase. No subscription.", "Only used to read prices.", "Open Settings", "per %@", "period",
        "Point at any price.", "Privacy", "Privacy Policy", "Pro", "Purchase Error", "Rates updated successfully",
        "Restore Purchases", "Scan", "Search", "See it in your money.", "Settings", "Start Free Trial", "Step %lld of %lld",
        "Subscribe", "Subscribe to use Tagwise", "Subscription", "Supported Currencies", "Swap currencies",
        "Tagwise respects your privacy. Your currency preferences and exchange rates are stored only on your device.",
        "Terms of Use", "Try again", "Turn on Camera for Tagwise in Settings to scan prices.",
        "Turn on location in Settings", "Unlock camera scanning forever.\nPay once. No subscription.", "Unlock Forever",
        "Unlock Forever for %@", "Unlock Tagwise", "Update Rates Now", "Version", "Wait — one-time offer",
        "We convert to this.", "week", "Weekly", "year", "Your home currency."]

_VALUES = {
    "nl": ["%1$@, daarna %2$@.", "%@. Valuta wijzigen", "%lld%% korting op Levenslang", "Een prijskaartje van %1$@, omgerekend naar %2$@.",
           "Over", "Actief", "Alle gegevens blijven op je toestel", "Camera toestaan", "Sta de camera toe.", "Wordt automatisch verlengd, altijd opzegbaar.",
           "Voordeligst", "Rekenmachine", "Cameratoegang staat uit", "Zoekopdracht wissen", "Sluiten", "Doorgaan",
           "De aankoop is mislukt. Probeer het opnieuw.", "Abonnementen laden mislukt. Controleer je verbinding.",
           "Wisselkoersdienst niet bereikbaar.", "De nieuwste koersen konden niet worden gelezen. Probeer het later.", "Valuta", "dag",
           "Lokale valuta herkennen", "Wisselkoersen",
           "Wisselkoersen worden offline opgeslagen en bijgewerkt als je internet hebt.", "%@ gratis",
           "Aan de slag", "Thuisvaluta", "Thuisvaluta: %@. Tik om te wijzigen.", "Laatst bijgewerkt", "Levenslang",
           "Abonnement beheren", "maand", "Maandelijks", "Populairst", "Geen account nodig", "Geen advertenties of tracking",
           "Geen verbinding. Koersen worden bijgewerkt zodra je online bent.", "Geen valuta gevonden voor ‘%@’", "Nee, bedankt", "Niet nu",
           "Geen abonnement", "OK", "eenmalig", "Eenmalige aankoop van %@. Geen abonnement.",
           "Eenmalige aankoop. Geen abonnement.", "Alleen om prijzen te lezen.", "Open Instellingen", "per %@", "periode",
           "Richt op een prijs.", "Privacy", "Privacybeleid", "Pro", "Aankoopfout", "Koersen bijgewerkt",
           "Aankopen herstellen", "Scannen", "Zoeken", "Zie het in je eigen valuta.", "Instellingen", "Start gratis proefperiode", "Stap %1$lld van %2$lld",
           "Abonneren", "Neem een abonnement om Tagwise te gebruiken", "Abonnement", "Ondersteunde valuta's", "Valuta's omwisselen",
           "Tagwise respecteert je privacy. Je valuta en wisselkoersen worden alleen op je toestel opgeslagen.",
           "Gebruiksvoorwaarden", "Opnieuw proberen", "Zet de camera voor Tagwise aan in Instellingen om prijzen te scannen.",
           "Zet locatie aan in Instellingen", "Scan met je camera, voor altijd.\nEén keer betalen. Geen abonnement.", "Voor altijd ontgrendelen",
           "Voor altijd ontgrendelen voor %@", "Ontgrendel Tagwise", "Koersen nu bijwerken", "Versie", "Wacht — eenmalige aanbieding",
           "Hiernaar rekenen we om.", "week", "Wekelijks", "jaar", "Je thuisvaluta."],
    "ru": ["%1$@, затем %2$@.", "%@. Сменить валюту", "Скидка %lld%% на «Навсегда»", "Ценник %1$@, в пересчёте %2$@.",
           "О приложении", "Активна", "Все данные хранятся на устройстве", "Разрешить камеру", "Разрешите камеру.", "Продлевается автоматически, отмена в любой момент.",
           "Выгоднее всего", "Калькулятор", "Доступ к камере выключен", "Очистить поиск", "Закрыть", "Продолжить",
           "Не удалось завершить покупку. Попробуйте снова.", "Не удалось загрузить тарифы. Проверьте подключение.",
           "Сервис курсов валют недоступен.", "Не удалось получить свежие курсы. Попробуйте позже.", "Валюта", "день",
           "Определять местную валюту", "Курсы валют",
           "Курсы хранятся офлайн и обновляются при подключении к интернету.", "Бесплатно %@",
           "Начать", "Домашняя валюта", "Домашняя валюта: %@. Нажмите, чтобы изменить.", "Обновлено", "Навсегда",
           "Управлять подпиской", "месяц", "Ежемесячно", "Популярный", "Без аккаунта", "Без рекламы и слежки",
           "Нет подключения. Курсы обновятся, когда вы будете онлайн.", "Нет валюты по запросу «%@»", "Нет, спасибо", "Не сейчас",
           "Нет подписки", "OK", "разово", "Разовая покупка за %@. Без подписки.",
           "Разовая покупка. Без подписки.", "Только для чтения цен.", "Открыть Настройки", "в %@", "период",
           "Наведите на любую цену.", "Конфиденциальность", "Политика конфиденциальности", "Pro", "Ошибка покупки", "Курсы обновлены",
           "Восстановить покупки", "Сканер", "Поиск", "Сразу в вашей валюте.", "Настройки", "Начать бесплатный период", "Шаг %1$lld из %2$lld",
           "Подписаться", "Оформите подписку, чтобы пользоваться Tagwise", "Подписка", "Поддерживаемые валюты", "Поменять валюты местами",
           "Tagwise уважает вашу конфиденциальность. Выбранные валюты и курсы хранятся только на вашем устройстве.",
           "Условия использования", "Повторить", "Включите камеру для Tagwise в Настройках, чтобы сканировать цены.",
           "Включите геолокацию в Настройках", "Сканирование камерой навсегда.\nОдин платёж. Без подписки.", "Открыть навсегда",
           "Открыть навсегда за %@", "Откройте Tagwise", "Обновить курсы", "Версия", "Подождите — разовое предложение",
           "В неё и пересчитываем.", "неделя", "Еженедельно", "год", "Ваша домашняя валюта."],
    "tr": ["%1$@, ardından %2$@.", "%@. Para birimini değiştir", "Ömür Boyu'da %%%lld indirim", "%1$@ fiyat etiketi, %2$@ olarak çevrildi.",
           "Hakkında", "Etkin", "Tüm veriler cihazda", "Kameraya izin ver", "Kameraya izin verin.", "Otomatik yenilenir, istediğiniz zaman iptal edin.",
           "En avantajlı", "Hesap Makinesi", "Kamera erişimi kapalı", "Aramayı temizle", "Kapat", "Devam",
           "Satın alma tamamlanamadı. Tekrar deneyin.", "Planlar yüklenemedi. Bağlantınızı kontrol edin.",
           "Döviz kuru hizmetine ulaşılamadı.", "Güncel kurlar okunamadı. Daha sonra deneyin.", "Para birimi", "gün",
           "Yerel para birimini algıla", "Döviz Kurları",
           "Kurlar çevrimdışı saklanır ve internete bağlandığınızda güncellenir.", "%@ ücretsiz",
           "Başla", "Ana para birimi", "Ana para birimi: %@. Değiştirmek için dokunun.", "Son güncelleme", "Ömür Boyu",
           "Aboneliği yönet", "ay", "Aylık", "En popüler", "Hesap gerekmez", "Reklam ve takip yok",
           "Bağlantı yok. Kurlar çevrimiçi olduğunuzda güncellenecek.", "“%@” ile eşleşen para birimi yok", "Hayır, teşekkürler", "Şimdi değil",
           "Abone değil", "Tamam", "tek seferlik", "%@ tek seferlik satın alma. Abonelik yok.",
           "Tek seferlik satın alma. Abonelik yok.", "Yalnızca fiyatları okumak için.", "Ayarlar'ı aç", "%@ başına", "dönem",
           "Herhangi bir fiyata tutun.", "Gizlilik", "Gizlilik Politikası", "Pro", "Satın Alma Hatası", "Kurlar güncellendi",
           "Satın alımları geri yükle", "Tara", "Ara", "Kendi para biriminizde görün.", "Ayarlar", "Ücretsiz denemeyi başlat", "Adım %1$lld / %2$lld",
           "Abone ol", "Tagwise'ı kullanmak için abone olun", "Abonelik", "Desteklenen para birimleri", "Para birimlerini değiştir",
           "Tagwise gizliliğinize saygı duyar. Para birimi tercihleriniz ve kurlar yalnızca cihazınızda saklanır.",
           "Kullanım Koşulları", "Tekrar dene", "Fiyat taramak için Ayarlar'dan Tagwise kamerasını açın.",
           "Ayarlar'dan konumu açın", "Kamerayla tarama, kalıcı olarak.\nTek ödeme. Abonelik yok.", "Kalıcı olarak aç",
           "%@ karşılığında kalıcı aç", "Tagwise'ın kilidini açın", "Kurları şimdi güncelle", "Sürüm", "Bekleyin — tek seferlik teklif",
           "Buna çeviriyoruz.", "hafta", "Haftalık", "yıl", "Ana para biriminiz."],
    "th": ["%1$@ จากนั้น %2$@", "%@ เปลี่ยนสกุลเงิน", "ลด %lld%% แบบตลอดชีพ", "ป้ายราคา %1$@ แปลงเป็น %2$@",
           "เกี่ยวกับ", "ใช้งานอยู่", "ข้อมูลทั้งหมดเก็บในเครื่อง", "อนุญาตกล้อง", "อนุญาตให้ใช้กล้อง", "ต่ออายุอัตโนมัติ ยกเลิกได้ทุกเมื่อ",
           "คุ้มที่สุด", "เครื่องคิดเลข", "ปิดการเข้าถึงกล้องอยู่", "ล้างการค้นหา", "ปิด", "ดำเนินการต่อ",
           "ซื้อไม่สำเร็จ ลองอีกครั้ง", "โหลดแผนไม่สำเร็จ ตรวจสอบการเชื่อมต่อ",
           "เชื่อมต่อบริการอัตราแลกเปลี่ยนไม่ได้", "อ่านอัตราล่าสุดไม่ได้ ลองใหม่ภายหลัง", "สกุลเงิน", "วัน",
           "ตรวจหาสกุลเงินท้องถิ่น", "อัตราแลกเปลี่ยน",
           "อัตราแลกเปลี่ยนเก็บไว้แบบออฟไลน์ และอัปเดตเมื่อมีอินเทอร์เน็ต", "ฟรี %@",
           "เริ่มต้นใช้งาน", "สกุลเงินหลัก", "สกุลเงินหลัก: %@ แตะเพื่อเปลี่ยน", "อัปเดตล่าสุด", "ตลอดชีพ",
           "จัดการการสมัครสมาชิก", "เดือน", "รายเดือน", "ยอดนิยม", "ไม่ต้องมีบัญชี", "ไม่มีโฆษณาหรือการติดตาม",
           "ไม่มีการเชื่อมต่อ อัตราจะอัปเดตเมื่อออนไลน์", "ไม่พบสกุลเงินที่ตรงกับ “%@”", "ไม่ล่ะ ขอบคุณ", "ไว้ทีหลัง",
           "ยังไม่ได้สมัคร", "ตกลง", "ครั้งเดียว", "ซื้อครั้งเดียว %@ ไม่ใช่การสมัครสมาชิก",
           "ซื้อครั้งเดียว ไม่ใช่การสมัครสมาชิก", "ใช้เพื่ออ่านราคาเท่านั้น", "เปิดการตั้งค่า", "ต่อ%@", "รอบ",
           "ส่องไปที่ราคาใดก็ได้", "ความเป็นส่วนตัว", "นโยบายความเป็นส่วนตัว", "Pro", "การซื้อผิดพลาด", "อัปเดตอัตราแล้ว",
           "กู้คืนการซื้อ", "สแกน", "ค้นหา", "เห็นเป็นสกุลเงินของคุณ", "การตั้งค่า", "เริ่มทดลองใช้ฟรี", "ขั้นตอนที่ %1$lld จาก %2$lld",
           "สมัครสมาชิก", "สมัครสมาชิกเพื่อใช้ Tagwise", "การสมัครสมาชิก", "สกุลเงินที่รองรับ", "สลับสกุลเงิน",
           "Tagwise เคารพความเป็นส่วนตัวของคุณ สกุลเงินที่เลือกและอัตราแลกเปลี่ยนเก็บไว้ในเครื่องของคุณเท่านั้น",
           "ข้อกำหนดการใช้งาน", "ลองอีกครั้ง", "เปิดกล้องสำหรับ Tagwise ในการตั้งค่าเพื่อสแกนราคา",
           "เปิดตำแหน่งในการตั้งค่า", "สแกนด้วยกล้องได้ตลอดไป\nจ่ายครั้งเดียว ไม่ต้องสมัครสมาชิก", "ปลดล็อกตลอดไป",
           "ปลดล็อกตลอดไปในราคา %@", "ปลดล็อก Tagwise", "อัปเดตอัตราตอนนี้", "เวอร์ชัน", "เดี๋ยวก่อน — ข้อเสนอครั้งเดียว",
           "เราแปลงเป็นสกุลนี้", "สัปดาห์", "รายสัปดาห์", "ปี", "สกุลเงินหลักของคุณ"],
    "id": ["%1$@, lalu %2$@.", "%@. Ganti mata uang", "Diskon %lld%% Seumur Hidup", "Label harga %1$@, dikonversi ke %2$@.",
           "Tentang", "Aktif", "Semua data tersimpan di perangkat", "Izinkan kamera", "Izinkan kamera.", "Diperpanjang otomatis, batalkan kapan saja.",
           "Paling hemat", "Kalkulator", "Akses kamera mati", "Hapus pencarian", "Tutup", "Lanjut",
           "Pembelian gagal. Coba lagi.", "Gagal memuat paket. Periksa koneksimu.",
           "Layanan kurs tidak dapat dijangkau.", "Gagal membaca kurs terbaru. Coba lagi nanti.", "Mata uang", "hari",
           "Deteksi mata uang lokal", "Kurs",
           "Kurs disimpan offline dan diperbarui saat ada internet.", "Gratis %@",
           "Mulai", "Mata uang utama", "Mata uang utama: %@. Ketuk untuk mengganti.", "Terakhir diperbarui", "Seumur Hidup",
           "Kelola langganan", "bulan", "Bulanan", "Terpopuler", "Tanpa akun", "Tanpa iklan atau pelacakan",
           "Tidak ada koneksi. Kurs diperbarui saat online.", "Tidak ada mata uang yang cocok dengan “%@”", "Tidak, terima kasih", "Nanti saja",
           "Belum berlangganan", "OK", "sekali bayar", "Pembelian sekali %@. Bukan langganan.",
           "Pembelian sekali. Bukan langganan.", "Hanya untuk membaca harga.", "Buka Pengaturan", "per %@", "periode",
           "Arahkan ke harga apa pun.", "Privasi", "Kebijakan Privasi", "Pro", "Kesalahan Pembelian", "Kurs diperbarui",
           "Pulihkan pembelian", "Pindai", "Cari", "Lihat dalam mata uangmu.", "Pengaturan", "Mulai uji coba gratis", "Langkah %1$lld dari %2$lld",
           "Berlangganan", "Berlangganan untuk memakai Tagwise", "Langganan", "Mata uang yang didukung", "Tukar mata uang",
           "Tagwise menghormati privasimu. Pilihan mata uang dan kurs hanya disimpan di perangkatmu.",
           "Ketentuan Penggunaan", "Coba lagi", "Nyalakan kamera untuk Tagwise di Pengaturan agar bisa memindai harga.",
           "Nyalakan lokasi di Pengaturan", "Pindai dengan kamera selamanya.\nSekali bayar. Tanpa langganan.", "Buka selamanya",
           "Buka selamanya seharga %@", "Buka Tagwise", "Perbarui kurs sekarang", "Versi", "Tunggu — penawaran sekali saja",
           "Kami konversi ke sini.", "minggu", "Mingguan", "tahun", "Mata uang utamamu."],
    "pt-PT": ["%1$@, depois %2$@.", "%@. Mudar moeda", "%lld%% de desconto no Vitalício", "Uma etiqueta de %1$@, convertida para %2$@.",
              "Acerca", "Ativa", "Todos os dados ficam no dispositivo", "Permitir câmara", "Permite a câmara.", "Renova automaticamente, cancela quando quiseres.",
              "Melhor preço", "Calculadora", "O acesso à câmara está desativado", "Limpar pesquisa", "Fechar", "Continuar",
              "Não foi possível concluir a compra. Tenta novamente.", "Não foi possível carregar os planos. Verifica a ligação.",
              "Não foi possível contactar o serviço de câmbio.", "Não foi possível ler as taxas mais recentes. Tenta mais tarde.", "Moeda", "dia",
              "Detetar moeda local", "Taxas de câmbio",
              "As taxas ficam guardadas offline e atualizam quando tens internet.", "Grátis durante %@",
              "Começar", "Moeda de casa", "Moeda de casa: %@. Toca para mudar.", "Última atualização", "Vitalício",
              "Gerir subscrição", "mês", "Mensal", "Mais popular", "Sem conta", "Sem anúncios nem rastreio",
              "Sem ligação. As taxas atualizam quando estiveres online.", "Nenhuma moeda corresponde a “%@”", "Não, obrigado", "Agora não",
              "Sem subscrição", "OK", "pagamento único", "Compra única de %@. Sem subscrição.",
              "Compra única. Sem subscrição.", "Só para ler preços.", "Abrir Definições", "por %@", "período",
              "Aponta a qualquer preço.", "Privacidade", "Política de privacidade", "Pro", "Erro na compra", "Taxas atualizadas",
              "Restaurar compras", "Digitalizar", "Pesquisar", "Vê na tua moeda.", "Definições", "Começar teste grátis", "Passo %1$lld de %2$lld",
              "Subscrever", "Subscreve para usar o Tagwise", "Subscrição", "Moedas suportadas", "Trocar moedas",
              "O Tagwise respeita a tua privacidade. As tuas moedas e taxas de câmbio ficam só no teu dispositivo.",
              "Termos de utilização", "Tentar novamente", "Ativa a câmara para o Tagwise nas Definições para digitalizar preços.",
              "Ativa a localização nas Definições", "Digitalização com a câmara para sempre.\nPagas uma vez. Sem subscrição.", "Desbloquear para sempre",
              "Desbloquear para sempre por %@", "Desbloqueia o Tagwise", "Atualizar taxas agora", "Versão", "Espera — oferta única",
              "Convertemos para esta.", "semana", "Semanal", "ano", "A tua moeda de casa."],
}

INFOPLIST = {
    "nl": ("Tagwise", "Tagwise gebruikt de camera om prijzen te lezen en om te rekenen.",
           "Tagwise gebruikt je locatie om op reis de lokale valuta te kiezen."),
    "ru": ("Tagwise", "Tagwise использует камеру, чтобы читать цены и пересчитывать их.",
           "Tagwise использует геопозицию, чтобы выбрать местную валюту в поездке."),
    "tr": ("Tagwise", "Tagwise, fiyatları okuyup çevirmek için kamerayı kullanır.",
           "Tagwise, seyahatte yerel para birimini seçmek için konumunuzu kullanır."),
    "th": ("Tagwise", "Tagwise ใช้กล้องเพื่ออ่านราคาและแปลงสกุลเงิน",
           "Tagwise ใช้ตำแหน่งของคุณเพื่อเลือกสกุลเงินท้องถิ่นเมื่อเดินทาง"),
    "id": ("Tagwise", "Tagwise memakai kamera untuk membaca dan mengonversi harga.",
           "Tagwise memakai lokasimu untuk memilih mata uang lokal saat bepergian."),
    "pt-PT": ("Tagwise", "O Tagwise usa a câmara para ler preços e convertê-los.",
              "O Tagwise usa a tua localização para escolher a moeda local quando viajas."),
}

for _lang, _vals in _VALUES.items():
    assert len(_vals) == len(KEYS), (_lang, len(_vals), len(KEYS))

MORE = {lang: dict(zip(KEYS, vals)) for lang, vals in _VALUES.items()}
INFOPLIST_KEYS = ["CFBundleDisplayName", "NSCameraUsageDescription", "NSLocationWhenInUseUsageDescription"]
MORE_INFOPLIST = {lang: dict(zip(INFOPLIST_KEYS, vals)) for lang, vals in INFOPLIST.items()}
